[package]
name = "moonblokz-storage-std-example"
version = "0.1.0"
edition = "2024"

[dependencies]
moonblokz-storage = { path = "../../", default-features = false, features = ["backend-memory"] }
moonblokz-chain-types = { git = "https://github.com/petersallai/moonblokz-chain-types" }
moonblokz-crypto = { git = "https://github.com/petersallai/moonblokz-crypto-lib", default-features = false, features = ["schnorr-crypto-bigint"] }
